#! /bin/sh
# /etc/init.d/runRadioControl

### BEGIN INIT INFO
# Provides:          runRadioControl
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Running Radio Control"
    # run application you want to start
    sudo /home/pi/PiLadyAnneRadio/scripts/radiocontrol.sh &
    ;;
  stop)
    echo "Stopping Radio Control"
    # kill application you want to stop
    sudo killall python
    ;;
  *)
    echo "Usage: /etc/init.d/runRadioControl {start|stop}"
    exit 1
    ;;
esac

exit 0


